const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const files = { '/': 'index.html', '/index.html': 'index.html', '/style.css': 'style.css', '/app.js': 'app.js', '/safety.js': 'safety.js', '/update-client.js': 'update-client.js', '/release.json': 'release.json', '/nickname.js': 'nickname.js', '/cat-faces.js': 'cat-faces.js', '/cat-roles.js': 'cat-roles.js', '/cat-scenes.js': 'cat-scenes.js', '/cat-day-scenes.js': 'cat-day-scenes.js', '/favicon.svg': 'favicon.svg', '/tonight-trend.js': 'tonight-trend.js', '/sleep-flow.js': 'sleep-flow.js', '/night-clock.js': 'night-clock.js', '/supabase-config.js': 'supabase-config.js', '/supabase-api.js': 'supabase-api.js', '/vendor/supabase.js': 'vendor/supabase.js' };
const types = { '.html': 'text/html', '.json': 'application/json', '.css': 'text/css', '.js': 'text/javascript', '.svg': 'image/svg+xml' };
files['/wild-cat-assets.js']='wild-cat-assets.js';
files['/cat-coat-cooldown.js']='cat-coat-cooldown.js';
files['/timeline-visibility.js']='timeline-visibility.js';
files['/roof-cats.js']='roof-cats.js';
files['/assets/roof-cats/rear-template.png']='assets/roof-cats/rear-template.png';
for(const pose of ['rear-upright','rear-relaxed','rear-rounded'])files[`/assets/roof-cats/${pose}.png`]=`assets/roof-cats/${pose}.png`;
for(const pose of ['storybook-upright','storybook-relaxed','storybook-rounded'])files[`/assets/roof-cats/${pose}.png`]=`assets/roof-cats/${pose}.png`;
for(const file of fs.readdirSync(path.join(__dirname,'assets/wild-cats')))if(/^[a-z-]+\.png$/.test(file))files['/assets/wild-cats/'+file]='assets/wild-cats/'+file;
types['.png']='image/png';
for(const period of ['morning','day','night'])files[`/assets/room-cats/calico-${period}.png`]=`assets/room-cats/calico-${period}.png`;
files['/assets/room-cats/calico-day-unified.png']='assets/room-cats/calico-day-unified.png';
types['.woff2']='font/woff2';
for(const file of fs.readdirSync(path.join(__dirname,'assets/fonts')))if(/^[a-z0-9-]+\.woff2$/.test(file))files['/assets/fonts/'+file]='assets/fonts/'+file;
for(const file of fs.readdirSync(path.join(__dirname,'assets/domestic-cats')))if(/^[a-z-]+\.png$/.test(file))files['/assets/domestic-cats/'+file]='assets/domestic-cats/'+file;
for(const file of fs.readdirSync(path.join(__dirname,'assets/big-cats')))if(/^[a-z-]+\.png$/.test(file))files['/assets/big-cats/'+file]='assets/big-cats/'+file;
for(const file of fs.readdirSync(path.join(__dirname,'assets/day-cats')))if(/^[a-z-]+\.png$/.test(file))files['/assets/day-cats/'+file]='assets/day-cats/'+file;
for(const file of fs.readdirSync(path.join(__dirname,'assets/sleep-wake-cats')))if(/^[a-z-]+-(?:sleeping|waking)\.png$/.test(file))files['/assets/sleep-wake-cats/'+file]='assets/sleep-wake-cats/'+file;
files['/cat-image-assets.js']='cat-image-assets.js';
files['/cat-care.js']='cat-care.js';
files['/cat-meal-assets.js']='cat-meal-assets.js';
files['/assets/cat-meals-v1/manifest.json']='assets/cat-meals-v1/manifest.json';
for(const coat of fs.readdirSync(path.join(__dirname,'assets/cat-meals-v1')))if(/^[a-z-]+$/.test(coat))for(const file of fs.readdirSync(path.join(__dirname,'assets/cat-meals-v1',coat)))if(/^(?:before|after)-[123]\.png$/.test(file))files['/assets/cat-meals-v1/'+coat+'/'+file]='assets/cat-meals-v1/'+coat+'/'+file;
for(const coat of fs.readdirSync(path.join(__dirname,'assets/cat-refresh-v1')))if(/^[a-z-]+$/.test(coat))for(const file of fs.readdirSync(path.join(__dirname,'assets/cat-refresh-v1',coat)))if(/^[a-z-]+\.png$/.test(file))files['/assets/cat-refresh-v1/'+coat+'/'+file]='assets/cat-refresh-v1/'+coat+'/'+file;
for(const file of fs.readdirSync(path.join(__dirname,'assets/roof-cats-v2')))if(/^[a-z-]+\.png$/.test(file))files['/assets/roof-cats-v2/'+file]='assets/roof-cats-v2/'+file;
for(const file of ['day-room.js','day-room.css','day-room-state.js','season-weather.js','season-landscape.js','assets/day-room/room.svg'])files['/'+file]=file;
http.createServer((req, res) => {
  const file = files[new URL(req.url, 'http://localhost').pathname];
  if (!file) { res.writeHead(404); return res.end('Not found'); }
  const extension=path.extname(file);
  res.setHeader('Content-Type', types[extension] + (['.png','.woff2'].includes(extension)?'':'; charset=utf-8'));
  if(extension==='.woff2')res.setHeader('Cache-Control','public, max-age=31536000, immutable');
  fs.createReadStream(path.join(__dirname, file)).pipe(res);
}).listen(Number(process.env.PORT) || 3000, '127.0.0.1', function () { console.log(`おやすみ: http://localhost:${this.address().port}`); });
