const assert = require('node:assert/strict');
require('./tonight-trend.js');
require('./wild-cat-assets.js');require('./cat-faces.js');
const t=TonightTrend;
const point=(minutes,awake)=>({time:minutes*60000,awake,sleeping:0});
const series=counts=>counts.map((count,index)=>point(index*15,count));
assert.equal(t.classify([],10),'insufficient');
assert.equal(t.classify([point(0,10)],10),'insufficient');
assert.equal(t.classify([point(0,10),point(10,20)],20),'insufficient');
assert.equal(t.classify(series([100,100,100])),'insufficient','Wait for confirmation');
assert.equal(t.classify(series([100,100,120,130])),'increasing');
assert.equal(t.classify(series([100,100,80,80,80])),'decreasing');
assert.equal(t.classify(series([100,100,40,40,40])),'strongDecreasing');
assert.equal(t.classify(series([100,100,100,100])),'steady');
assert.equal(t.classify(series([1,1,2,2])),'steady','Avoid small-denominator noise');
assert.equal(t.classify([...series([100,100,100,100]),point(46,1000)]),'steady','Ignore incomplete samples');
assert.equal(t.classify(series([100,100,100,100,101,99,100])),'steady','Short fluctuations must stay steady');
assert.equal(t.classify(series([100,100,120,130,0])),'increasing','Do not reverse in one interval');
assert.equal(t.classify(series([100,100,120,130,0,0])),'strongDecreasing','Sustained reversal can change after the hold period');
assert.equal(t.classify([...series([100,100,100,100]),point(90,100),point(105,100)]),'insufficient','Do not bridge observation gaps');
assert.equal(t.classify([...series([1,1,1,1]),...series([100,100,100,100,100,100,100,100]).map(p=>({...p,time:p.time+60*60000}))]),'steady','Old spikes must leave the 60-minute window');
assert(!t.chart([]).includes('<svg'));
assert(t.chart([point(0,0)]).includes('<circle'));
assert(!t.chart([point(0,0),point(30,0)]).includes('NaN'));
assert(!t.chart([point(0,2),point(30,4)]).includes('サンプル'));
const old=t.messages.steady;t.messages.steady='変更テスト';assert.equal(t.comment(series([100,100,100,100])),'変更テスト');t.messages.steady=old;
const threshold=t.rules.increaseRate;t.rules.increaseRate=1;assert.equal(t.classify(series([100,100,120,130])),'steady');t.rules.increaseRate=threshold;
const cats=new Set();
for(const coat of CatFaces.coats.filter(coat=>!WildCatAssets.isWild(coat.id)))for(const expression of CatFaces.options){
  const svg=CatFaces.svg(expression.id,coat.id);
  assert(svg.includes(`data-cat-coat="${coat.id}"`));assert(svg.includes(`data-cat-expression="${expression.id}"`));
  assert(svg.includes(`assets/domestic-cats/${coat.id}-faces-${expression.id}.png?v=`));assert(!svg.includes('cat.svg'));cats.add(svg);
}
assert.equal(cats.size,48);
assert.equal(CatFaces.normalizeCoat('<script>'),'calico');
assert.equal(CatFaces.normalize('<script>'),'calm');
console.log('PASS trend logic: five comments, observation gaps, recent comparison, editable copy, empty/zero graphs and 48 distinct SVG cats.');
