(()=>{
const memory=new Map();for(const key of ['localStorage','sessionStorage'])Object.defineProperty(window,key,{value:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)},configurable:true});localStorage.setItem('oyasumi-dark-hint-seen','preview');
const params=new URLSearchParams(location.search);globalThis.CarePreviewData={coat:params.get('coat')||'calico',user:params.get('user')==='receiver'?'00000000-0000-0000-0000-000000000002':'00000000-0000-0000-0000-000000000001',expression:'calm',calls:0,fail:false};
const rpc=async(kind,data={})=>{if(CarePreviewData.fail)throw Error('Preview network failure');if(kind==='meal'||kind==='treat')CarePreviewData.calls++;const response=await fetch('/__care/'+kind,{method:'POST',headers:{'Content-Type':'application/json','x-preview-user':CarePreviewData.user},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Object.assign(Error(result.message),{code:result.code});return result;};
const api={initialize:async()=>CarePreviewData.user,getCatCareStatus:()=>rpc('status'),giveCatMeal:()=>rpc('meal'),giveCatTreat:recipient=>rpc('treat',{recipient}),snapshot:async()=>{
 const user=CarePreviewData.user,other=user.endsWith('1')?'00000000-0000-0000-0000-000000000002':'00000000-0000-0000-0000-000000000001';
 const post={id:'preview-post',userId:other,name:'おとなりの猫',coat:CarePreviewData.coat,expression:CarePreviewData.expression,catRole:null,profileNote:'今日も、ひとやすみ。',status:'awake',time:Date.now(),self:false,color:'slate'};
 return {userId:user,name:user.endsWith('1')?'こむぎ':'おとなりの猫',coat:CarePreviewData.coat,expression:CarePreviewData.expression,profileNote:'今日も、ひとやすみ。',profileComplete:true,needsCat:false,needsNickname:false,ownPosts:[],feed:[post],reactions:{},reactionCounts:{},activeAwakePosts:[post],awakeCount:1,sleepingCount:1,ownSleepCount:1,nightDate:SleepFlow.night(Date.now()),trend:[],trendSupported:false,catCoatStatus:{nextChangeAt:null,temporarilyUnlocked:true},catCare:await rpc('status')};}};
Object.defineProperty(window,'OyasumiAPI',{get:()=>api,set:()=>{},configurable:true});globalThis.CarePreviewRPC=rpc;globalThis.previewErrors=[];addEventListener('error',e=>previewErrors.push(e.message||'resource'),true);addEventListener('unhandledrejection',e=>previewErrors.push(String(e.reason)));
})();